# This is a basic workflow to help you get started with Actions
name: API Load test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
        email:
          description: 'email'
          type: string
          required: true
        password:
          description: 'password'
          type: string
          required: true  
        vus:
          description: 'No of virtual users(eg 100)'
          type: string
          required: true    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: OnBoardApi-LoadTest.js
          flags: --out json=results.json
        env:
          UserName: ${{ inputs.email }}
          Password: ${{ inputs.password }}
          VUS: ${{ inputs.vus }}
          
      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json
          
      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
           name: k6-summary-report
           path: summary.json
